export enum ProductActionName {
  START_PRODUCTS_ACTION = 'START_PRODUCTS_ACTION',
  FETCH_PRODUCTS = 'FETCH_PRODUCTS',
  ADD_PRODUCT = 'ADD_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT'
}
